object TaskGremlinConst {
    const val RESULT_SUCCESS = "success"
    const val RESULT_LOCK_FAILURE = "lock-failure"

    const val FIELD_ID = "#id"
    const val FIELD_TITLE = "title"
    const val FIELD_EXECUTOR = "executor"
    const val FIELD_STAGE_LIST_ID = "stageListId"
    const val FIELD_STAGE_LIST_STAGE = "stageListStage"
    const val FIELD_STAGE_LIST_VALUE = "stageListValue"
    const val FIELD_STAGE_LIST_COMMENT = "stageListComment"
    const val FIELD_DEADLINE = "deadline"
    const val FIELD_ADDRESS = "address"
    const val FIELD_COMMENT = "comment"
    const val FIELD_PHOTO = "photo"
    const val FIELD_TASK_TYPE = "taskType"
    const val FIELD_CUSTOMER_ID = "customerId"
    const val FIELD_VISIBILITY = "visibility"
    const val FIELD_LOCK = "lock"
    const val FIELD_TMP_RESULT = "_result"
}
